
title: YOUR TITLE
description: YOUR DESCRIPTION
theme: just-the-docs

url: https://Aparna-T-Ashokan.github.io/Db2-developer-extension-staging-2

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/Aparna-T-Ashokan/Db2-developer-extension-staging-2

plugins:
  - jekyll-default-layout

